#alpine is a package which is much smaller. You can also choose ubutu as basic image by change it to FROM ubuntu:latest
FROM alpine
MAINTAINER Xi Eng Ops <canaveral@internal.nutanix.com>

# please add your own instruction below to build your docker image
CMD echo 'Hello, World'
